language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -q
install:
    - sudo apt install apr apr-util subversion boost1.55 protobuf google-glog gtest google-mock -y
    - wget https://raw.githubusercontent.com/kazuho/picojson/v1.3.0/picojson.h
    - sudo cp picojson.h /usr/locale/include/picojson.h
before_script:
    - mkdir build
    - cd build
    - cmake ../
    - make
script: make test
