language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -q
install:
    - sudo apt install libapr1-dev libaprutil1-dev libsvn-dev libboost1.55-all-dev libprotobuf-dev libgoogle-glog-dev libgtest-dev google-mock -y
    - wget https://raw.githubusercontent.com/kazuho/picojson/v1.3.0/picojson.h
    - sudo cp picojson.h /usr/local/include/picojson.h
before_script:
    - mkdir build
    - cd build
    - cmake ../
    - make
script: make test
